### ISSUE TITLE
实现手动滑的心电图

### ISSUE THREAD

**Issue by wangzq1992** [xuxichen/OC-ECGView#1]
你好，我们要实现一个手动滑的心电图，如果一次性绘制的话需要很长时间，而且cpu基本在%90以上，您有什么好的建议或者好的想法，可以请教一下吗，我想了几种方法，但实现起来出现了问题。

**Comment by zhangjianjun056** [comment]
你好，请问一下，我们通过心电仪测出的数据是2048左右徘徊的一些数据，但是我把从血压仪上拿到的数据减去2048处理之后，再展示就会出现问题：波形图呈一条直线，有的区间都挤在一起，请问大神有什么好的解决办法吗？

**Comment by wangzq1992** [comment]
你的数据经过滤波处理了嘛，减完之后的值是多少呢，这个如果太小的话也需要放大倍数的吧

**Comment by xuxichen** [comment]
@wangzq1992 不好意思，前段时间你的issues我忘记回复了，不过，这么久你应该解决了吧。因为我的数据其实是拿着我项目中介绍的另外一个项目中的数据，所以我对这个数据不是很清楚，我并没有做过心电图的功能，这只是我写的UI小demo，不过很乐意与你讨论相关的问题。我在玩自己的项目中是对数据的峰值后压缩到到我试图的3/5的高度。主要是为了看起来更清楚。我主要是在UI层面的考虑，对数据方面并没有太深刻的认识

**Comment by xuxichen** [comment]
@zhangjianjun056 因为我没有看到你的数据是什么样子的，所以不太清楚你说的情况，你能提供一些图片看看你的问题么？

**Comment by wangzq1992** [comment]
@xuxichen 还没有解决，先搁置了，暂时还没有滑动长时间数据的需求，不过我看别人已经实现了，就想看看怎么做的。有兴趣的话可以讨论一下，感觉别人的思路和实现效果方面做的都很好。

**Comment by wangzq1992** [comment]
@zhangjianjun056 ，你的数据经过滤波处理了嘛，减完之后的值是多少呢，这个如果太小的话也需要放大倍数的吧

**Comment by xuxichen** [comment]
@wangzq1992 在哪里？没看见你star或者follow那个项目呢？对于你说的CPU 的问题，我这个是用GPU实现的，所以不知道怎么会CPU占用很大。

**Comment by wangzq1992** [comment]
@xuxichen ，嗯我之前用的drawRect那个方法，周末我整理一下，发出来可以么。大家一起看一下，我没怎么用github

**Comment by xuxichen** [comment]
@wangzq1992 好的

**Comment by zhangjianjun056** [comment]
@xuxichen 你好，我处理之后的数据如下，心电图挤在一起，具体的截图和demo已经发大神邮箱了，请大神帮忙看一下，谢谢了。
-4,-4,-3,-2,-1,
        0,0,1,2,4,
        5,7,10,11,11,
        11,9,7,5,2,
        -1,-4,-20,-20,-3,
        38,63,63,53,11,
        -23,-23,-15,-7,-6,
        -6,-7,-7,-6,-1,
        9,16,16,14,13,
        12,12,13,13,14,
        14,16,19,22,24,
        26,30,34,40,46,
        54,62,71,81,91,
        100,106,108,105,99,
        90,77,62,46,31,
        17,6,-3,-9,-13,
        -16,-18,-20,-21,-20,
        -19,-18,-18,-17,-17,
        -16,-15,-14,-13,-11,
        -9,-6,-3,0,2,
        3,3,3,3,2,
        1,0,0,1,1,
        2,2,3,3,3,
        2,2,2,2,1,

**Comment by zhangjianjun056** [comment]
@xuxichen ，@wangzq1992  你好，我处理之后的数据如下，心电图挤在一起，具体的截图和demo已经发大神邮箱了，请大神帮忙看一下，谢谢了。
-4,-4,-3,-2,-1,
0,0,1,2,4,
5,7,10,11,11,
11,9,7,5,2,
-1,-4,-20,-20,-3,
38,63,63,53,11,
-23,-23,-15,-7,-6,
-6,-7,-7,-6,-1,
9,16,16,14,13,
12,12,13,13,14,
14,16,19,22,24,
26,30,34,40,46,
54,62,71,81,91,
100,106,108,105,99,
90,77,62,46,31,
17,6,-3,-9,-13,
-16,-18,-20,-21,-20,
-19,-18,-18,-17,-17,
-16,-15,-14,-13,-11,
-9,-6,-3,0,2,
3,3,3,3,2,
1,0,0,1,1,
2,2,3,3,3,
2,2,2,2,1,

**Comment by xuxichen** [comment]
@zhangjianjun056 你的demo我没看到，你加我QQ吧，490602680

**Comment by zhangjianjun056** [comment]
@xuxichen 嗯嗯，好的，多谢多谢
